#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/sprite.h"
#include "images/ticketmaster.h"
#include "images/lostgamescreen.h"
#include "images/taylorswiftsing.h"
#include "images/wingamescreen.h"
#include "images/kanyewest.h"
#include "images/snake.h"
#include "images/startscreen.h"
#include "images/blackbox.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

void delay (int n) {
  volatile int x = 0;
  for (int i = 0; i < n * 8000; i++) {
    x++;
  }
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  struct obstacles obstacles[15] = {
    {30, 110, 0, 0, 1},
    {60, 130, 0, 0, 3},
    {130, 200, 0, 0, 2},
    {40, 150, 0, 0, 3},
    {90, 80, 0, 0, 1},
    {110, 180, 0, 0, 2},
    {10, 80, 0, 0, 3},
    {60, 40, 0, 0, 1},
    {10, 80, 0, 0, 1},
    {50, 180, 0, 0, 2},
    {80, 40, 0, 0, 3},
    {120, 100, 0, 0, 1}, 
    {80, 200, 0, 0, 2},
    {80, 150 , 0, 0, 3},
    {120, 170, 0, 0, 1}
  };
  int object = sizeof(obstacles) / sizeof(obstacles[0]);
  for (int i = 0; i < object; i++) {
    if (obstacles[i].type == 1) {
      obstacles[i].height = TICKETMASTER_HEIGHT;
      obstacles[i].width = TICKETMASTER_WIDTH;
    } else if (obstacles[i].type == 2) {
      obstacles[i].height = KANYEWEST_HEIGHT;
      obstacles[i].width = KANYEWEST_WIDTH;
    } else if (obstacles[i].type == 3) {
      obstacles[i].height = SNAKE_HEIGHT;
      obstacles[i].width = SNAKE_WIDTH;
    }
  }
  struct sprite tay = {40, 100, SPRITE_WIDTH, SPRITE_HEIGHT, 2, 2};
  struct taylor goal = {70, 220, TAYLORSWIFTSING_WIDTH, TAYLORSWIFTSING_HEIGHT};

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  unsigned int count = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        tay.row = 80;
        tay.col = 10;
        tay.height = SPRITE_HEIGHT;
        tay.width = SPRITE_WIDTH;
        tay.uvel = 2;
        tay.hvel = 2;

        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(startscreen);
        }
        drawCenteredString(120, 120, 0, 0, "Get to the Eras Tour Concert ASAP", 0xFFFF);
        drawCenteredString(140, 120, 0, 0, "(Press START to continue)", 0xFFFF);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
          vBlankCounter = 0;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        // state = ?
        previousButtons = BUTTONS;
        count++;
        break;
      case PLAY:
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        int prevrow = tay.row;
        int prevcol = tay.col;
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          tay.row -= tay.uvel;
          if (tay.row < 0) {
            tay.row = 0;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          tay.row += tay.uvel;
          if (tay.row > HEIGHT - tay.height) {
            tay.row = HEIGHT - tay.height;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          tay.col -= tay.hvel;
          if (tay.col < 0) {
            tay.col = 0;
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          tay.col += tay.hvel;
          if (tay.col > WIDTH - tay.width) {
            tay.col = WIDTH - tay.width;
          }
        }
        if ((SCORE_COL <= tay.col + tay.width && SCORE_COL + 60 - 1 >= tay.col) && (SCORE_ROW <= tay.row + tay.height && SCORE_ROW + 10 - 1 >= tay.row)) {
          tay.col = prevcol;
          tay.row = prevrow;
        }
        int hit = 0;
        for (int i = 0; i < object; i++) {
          if ((obstacles[i].col + 1 <= tay.col + tay.width && obstacles[i].col + obstacles[i].width - 1 >= tay.col)
          && (obstacles[i].row + 1 <= tay.row + tay.height && obstacles[i].row + obstacles[i].height - 1 >= tay.row)) {
            waitForVBlank();
            delay(10);
            state = LOSE;
            count = 0;
            previousButtons = BUTTONS;
            hit = 1;
            break;
          }
        }
        if ((goal.col + 2 <= tay.col + tay.width && goal.col + goal.width - 2 >= tay.col)
          && (goal.row <= tay.row + tay.height && goal.row + goal.height - 2 >= tay.row)) {
            delay(10);
            state = WIN;
            count = 0;
            previousButtons = BUTTONS;
            hit = 1;
            break;
          }
        if (hit) {
          break;
        }
        char buffer[50];
        int time = vBlankCounter / 6;
        sprintf(buffer, "Score: %d", time);
        waitForVBlank();
        if (count == 0) {
          fillScreenDMA(BLACK);
          for (int i = 0; i < object; i++) {
            if (obstacles[i].type == 1) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, ticketmaster);
            } else if (obstacles[i].type == 2) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, kanyewest);
            } else if (obstacles[i].type == 3) {
              drawImageDMA(obstacles[i].row, obstacles[i].col, obstacles[i].width, obstacles[i].height, snake);
            }
          }
          drawImageDMA(goal.row, goal.col, goal.width, goal.height, taylorswiftsing);
        } else {
          undrawImageDMA(prevrow, prevcol, tay.width, tay.height, blackbox);
          drawImageDMA(tay.row, tay.col, tay.width, tay.height, sprite);
          undrawImageDMA(10, 180, 60, 10, blackbox);
          drawString(10, 180, buffer, 0xFFFF);
        }
        // state = ?
        count++;
        previousButtons = BUTTONS;
        break;
      case WIN:
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(wingamescreen);
        } else {
          sprintf(buffer, "Final Score: %d", time);
          drawString(40, 20, "You made it to the concert!", 0xFFFF);
          drawString(60, 130, buffer, 0xFFFF);
        }
        // state = ?
        count++;
        break;
      case LOSE:
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
          count = 0;
          previousButtons = BUTTONS;
          break;
        }
        waitForVBlank();
        if (count == 0) {
          drawFullScreenImageDMA(lostgamescreen);
        } else {
          drawCenteredString(120, 120, 0, 0, "You didn't make it to the concert...", 0xFFFF);
        }
        // state = ?
        count++;
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
